name: Sanjay Banerjee
favicon: null
layout_spectrum: 0.20255190134048462
typography_spectrum: 0.027290743310004473
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9630831927061081
  lightness: 0.2268586594145745
  saturation: 0.4140395075082779
  rhythmicContrast: 0.05905171204358339
purpose: []
